name: GitHub Actions CI Pipeline

on:
  push:
    branches: [ "docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker buildx  build -t "${{ secrets.DOCKER_USERNAME }}/cicd-pipeline:docker" .
    - name: Push to Dockerhub
      run: docker buildx push ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline:docker"


